#!/usr/bin/env node
import { Server as McpServer } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { readFile, writeFile } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import crypto from "crypto";
import postgres from "postgres";

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

function asObject(v: unknown): Record<string, unknown> | null {
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}

function env(name: string): string {
  return (process.env[name] || "").trim();
}

function redact(value: string) {
  if (!value) return "";
  if (value.length <= 8) return "********";
  return `${value.slice(0, 3)}…${value.slice(-3)}`;
}

function nowIso() {
  return new Date().toISOString();
}

function mustGetFromArgsOrEnv(name: string, args: Record<string, unknown>) {
  const v = typeof args[name] === "string" ? String(args[name]).trim() : env(name);
  return v;
}

function parseSupabaseProjectRefFromDbUrl(dbUrl: string): string | null {
  // Typical: postgres://...@db.<ref>.supabase.co:5432/postgres
  try {
    const u = new URL(dbUrl);
    const host = u.hostname; // db.<ref>.supabase.co
    const m = host.match(/^db\.([a-z0-9-]+)\.supabase\.co$/i);
    return m?.[1] ?? null;
  } catch {
    return null;
  }
}

async function fetchJson(url: string, init: RequestInit & { timeoutMs?: number } = {}) {
  const timeoutMs = init.timeoutMs ?? 12_000;
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...init, signal: ctrl.signal });
    const text = await res.text();
    let json: unknown = null;
    try {
      json = text ? JSON.parse(text) : null;
    } catch {
      json = null;
    }
    return { ok: res.ok, status: res.status, text, json };
  } finally {
    clearTimeout(t);
  }
}

function toEnvFileString(values: Record<string, string>) {
  const lines: string[] = [];
  lines.push(`# Generated by secrets-manager MCP (${nowIso()})`);
  for (const [k, v] of Object.entries(values)) {
    // Preserve newlines by JSON-stringifying when needed
    const safe =
      v.includes("\n") || v.includes("\r") ? JSON.stringify(v) : v.replaceAll("\r", "").replaceAll("\n", "");
    lines.push(`${k}=${safe}`);
  }
  lines.push("");
  return lines.join("\n");
}

function base64url(buf: Buffer) {
  return buf.toString("base64url");
}

async function encryptAesGcm(params: { plaintext: string; passphrase: string }) {
  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const key = await new Promise<Buffer>((resolve, reject) => {
    crypto.scrypt(params.passphrase, salt, 32, (err, derived) => (err ? reject(err) : resolve(derived as Buffer)));
  });
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const ct = Buffer.concat([cipher.update(params.plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return {
    scheme: "aes-256-gcm+scrypt",
    salt: base64url(salt),
    iv: base64url(iv),
    tag: base64url(tag),
    ciphertext: base64url(ct),
    payload: `v1.${base64url(salt)}.${base64url(iv)}.${base64url(tag)}.${base64url(ct)}`,
  };
}

function assertSimpleIdentifier(name: string) {
  if (!/^[a-zA-Z0-9_.-]{1,128}$/.test(name)) {
    throw new Error("Invalid secret name. Use letters/numbers/._- only (max 128 chars).");
  }
}

async function ensureFallbackSecretsTable(db: ReturnType<typeof postgres>) {
  await db.unsafe(`
    create schema if not exists secrets_manager;
    create table if not exists secrets_manager.secrets (
      name text primary key,
      encrypted_value text not null,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now()
    );
  `);
}

const CreateEnvFileInput = z.object({
  path: z.string().optional().default(".env.local"),
  values: z.record(z.string()).optional().default({}),
  overwrite: z.boolean().optional().default(false),
  generate_missing: z.boolean().optional().default(true),
});

const ValidateApiKeysInput = z.object({
  // Allow passing directly, but default to env vars.
  DATABASE_URL: z.string().optional(),
  SUPABASE_KEY: z.string().optional(),
  WHOIS_API_KEY: z.string().optional(),
  PAGESPEED_API_KEY: z.string().optional(),
  ELEVEN_LABS_API_KEY: z.string().optional(),
  RESEND_API_KEY: z.string().optional(),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TELEGRAM_BOT_TOKEN: z.string().optional(),
  APIFY_TOKEN: z.string().optional(),
  test_domain: z.string().optional().default("example.com"),
});

const EncryptSecretsInput = z.object({
  plaintext: z.string().min(1),
  passphrase: z.string().min(12),
});

const RotateCredentialsInput = z.object({
  // What to rotate is org-dependent; this tool generates fresh tokens + a checklist.
  include_cron_secret: z.boolean().optional().default(true),
  include_app_tokens: z.boolean().optional().default(true),
  token_bytes: z.number().int().min(16).max(128).optional().default(48),
});

const StoreInSupabaseVaultInput = z.object({
  name: z.string().min(1),
  value: z.string().min(1),
  pg_url: z.string().optional(),
  passphrase: z.string().optional(), // if omitted, uses SECRETS_MANAGER_MASTER_KEY
});

const GenerateSecureTokensInput = z.object({
  count: z.number().int().min(1).max(50).optional().default(5),
  bytes: z.number().int().min(16).max(128).optional().default(48),
});

const server = new McpServer({ name: "secrets-manager", version: "0.1.0" }, { capabilities: { tools: {} } });

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "create-env-file",
        description: "Create a `.env.local`-style file from provided key/values (with safe defaults).",
        inputSchema: {
          type: "object",
          properties: {
            path: { type: "string", description: "Target path (default: .env.local)." },
            values: { type: "object", additionalProperties: { type: "string" }, description: "Env var key/value pairs." },
            overwrite: { type: "boolean", description: "Overwrite existing file (default false)." },
            generate_missing: { type: "boolean", description: "Generate CRON_SECRET if missing (default true)." },
          },
        },
      },
      {
        name: "validate-api-keys",
        description: "Validate configured API keys by making test calls; errors immediately on any invalid key.",
        inputSchema: {
          type: "object",
          properties: {
            DATABASE_URL: { type: "string" },
            SUPABASE_KEY: { type: "string" },
            WHOIS_API_KEY: { type: "string" },
            PAGESPEED_API_KEY: { type: "string" },
            ELEVEN_LABS_API_KEY: { type: "string" },
            RESEND_API_KEY: { type: "string" },
            TWILIO_ACCOUNT_SID: { type: "string" },
            TWILIO_AUTH_TOKEN: { type: "string" },
            TELEGRAM_BOT_TOKEN: { type: "string" },
            APIFY_TOKEN: { type: "string" },
            test_domain: { type: "string", description: "Domain used for lightweight checks (default: example.com)." },
          },
        },
      },
      {
        name: "encrypt-secrets",
        description: "Encrypt a secret using AES-256-GCM with scrypt key derivation; returns a portable payload string.",
        inputSchema: {
          type: "object",
          properties: {
            plaintext: { type: "string" },
            passphrase: { type: "string", description: "Min 12 chars; store in a password manager." },
          },
          required: ["plaintext", "passphrase"],
        },
      },
      {
        name: "rotate-credentials",
        description: "Generate fresh secure tokens and a rotation checklist (manual rotation for external providers).",
        inputSchema: {
          type: "object",
          properties: {
            include_cron_secret: { type: "boolean" },
            include_app_tokens: { type: "boolean" },
            token_bytes: { type: "number" },
          },
        },
      },
      {
        name: "store-in-supabase-vault",
        description:
          "Store a secret in Supabase Vault (if available) or a fallback encrypted Postgres table using DATABASE_URL/pg_url.",
        inputSchema: {
          type: "object",
          properties: {
            name: { type: "string" },
            value: { type: "string" },
            pg_url: { type: "string", description: "Optional Postgres URL override; defaults to DATABASE_URL." },
            passphrase: { type: "string", description: "Optional; defaults to SECRETS_MANAGER_MASTER_KEY env var." },
          },
          required: ["name", "value"],
        },
      },
      {
        name: "generate-secure-tokens",
        description: "Generate cryptographically secure random tokens (base64url).",
        inputSchema: {
          type: "object",
          properties: { count: { type: "number" }, bytes: { type: "number" } },
        },
      },
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const name = req.params.name;
  const args = (req.params.arguments ?? {}) as Json;
  const obj = asObject(args) ?? {};

  if (name === "create-env-file") {
    const parsed = CreateEnvFileInput.parse(obj);
    const outPath = parsed.path;
    const abs = join(repoRoot(), outPath);
    if (existsSync(abs) && !parsed.overwrite) {
      throw new Error(`Refusing to overwrite existing ${outPath}. Pass overwrite=true to replace it.`);
    }

    const values: Record<string, string> = { ...parsed.values };
    if (parsed.generate_missing) {
      if (!values.CRON_SECRET) values.CRON_SECRET = base64url(crypto.randomBytes(48));
    }

    await writeFile(abs, toEnvFileString(values), "utf8");
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              ok: true,
              path: outPath,
              wrote: Object.keys(values).sort(),
              note: "Never commit this file. Prefer platform secrets or a dedicated secrets manager.",
            },
            null,
            2,
          ),
        },
      ],
    };
  }

  if (name === "generate-secure-tokens") {
    const parsed = GenerateSecureTokensInput.parse(obj);
    const tokens = Array.from({ length: parsed.count }, () => base64url(crypto.randomBytes(parsed.bytes)));
    return { content: [{ type: "text", text: JSON.stringify({ tokens }, null, 2) }] };
  }

  if (name === "encrypt-secrets") {
    const parsed = EncryptSecretsInput.parse(obj);
    const encrypted = await encryptAesGcm(parsed);
    return { content: [{ type: "text", text: JSON.stringify(encrypted, null, 2) }] };
  }

  if (name === "rotate-credentials") {
    const parsed = RotateCredentialsInput.parse(obj);
    const generated: Record<string, string> = {};
    if (parsed.include_cron_secret) generated.CRON_SECRET = base64url(crypto.randomBytes(parsed.token_bytes));
    if (parsed.include_app_tokens) {
      generated.SESSION_SECRET = base64url(crypto.randomBytes(parsed.token_bytes));
      generated.WEBHOOK_SIGNATURE_SECRET = base64url(crypto.randomBytes(parsed.token_bytes));
    }
    const checklist = [
      "Update secrets in your platform/secret manager (Vercel/Doppler/etc.).",
      "Re-deploy services that depend on the rotated secrets.",
      "For third-party API keys (Twilio/Resend/etc.), rotate in provider dashboard and update env vars.",
      "Invalidate old keys/tokens where the provider supports it.",
      "Run `validate-api-keys` after rotation to ensure all integrations still work.",
    ];
    return { content: [{ type: "text", text: JSON.stringify({ generated, checklist }, null, 2) }] };
  }

  if (name === "store-in-supabase-vault") {
    const parsed = StoreInSupabaseVaultInput.parse(obj);
    assertSimpleIdentifier(parsed.name);
    const pgUrl = (parsed.pg_url || env("DATABASE_URL")).trim();
    if (!pgUrl) throw new Error("DATABASE_URL (or pg_url) is required to store secrets in Postgres.");

    const passphrase = (parsed.passphrase || env("SECRETS_MANAGER_MASTER_KEY")).trim();
    if (!passphrase) {
      throw new Error("passphrase is required (or set SECRETS_MANAGER_MASTER_KEY) to encrypt before storage.");
    }

    const encrypted = await encryptAesGcm({ plaintext: parsed.value, passphrase });
    const db = postgres(pgUrl, { max: 3, prepare: false });
    try {
      // Try Supabase Vault first if installed.
      const probe = await db<{ ok: boolean }[]>`
        select exists(
          select 1 from pg_proc p
          join pg_namespace n on n.oid = p.pronamespace
          where n.nspname = 'vault' and p.proname in ('create_secret','upsert_secret')
        ) as ok
      `;
      const hasVault = Boolean(probe?.[0]?.ok);

      if (hasVault) {
        // Prefer upsert if present.
        const upsertExists = await db<{ ok: boolean }[]>`
          select exists(
            select 1 from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'vault' and p.proname = 'upsert_secret'
          ) as ok
        `;
        const canUpsert = Boolean(upsertExists?.[0]?.ok);
        if (canUpsert) {
          await db.unsafe(`select vault.upsert_secret($1, $2)`, [parsed.name, encrypted.payload]);
        } else {
          // create_secret may not allow updates; we still attempt.
          await db.unsafe(`select vault.create_secret($1, $2)`, [parsed.name, encrypted.payload]);
        }
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(
                { ok: true, stored_in: "supabase_vault", name: parsed.name, encrypted: true, scheme: encrypted.scheme },
                null,
                2,
              ),
            },
          ],
        };
      }

      // Fallback: encrypted table (still safe-ish, but DBAs can access it; prefer a real secrets manager).
      await ensureFallbackSecretsTable(db);
      await db`
        insert into secrets_manager.secrets (name, encrypted_value)
        values (${parsed.name}, ${encrypted.payload})
        on conflict (name) do update
          set encrypted_value = excluded.encrypted_value,
              updated_at = now()
      `;
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                ok: true,
                stored_in: "postgres_fallback_table",
                table: "secrets_manager.secrets",
                name: parsed.name,
                encrypted: true,
                scheme: encrypted.scheme,
                warning:
                  "Supabase Vault was not detected. Prefer a platform secrets manager or install Vault; DB admins can still read encrypted blobs.",
              },
              null,
              2,
            ),
          },
        ],
      };
    } finally {
      await db.end({ timeout: 5 });
    }
  }

  if (name === "validate-api-keys") {
    const parsed = ValidateApiKeysInput.parse(obj);
    const testDomain = (parsed.test_domain || "example.com").trim() || "example.com";
    const issues: Array<{ service: string; ok: boolean; status?: number; detail: string }> = [];

    const DATABASE_URL = (parsed.DATABASE_URL || env("DATABASE_URL")).trim();
    const SUPABASE_KEY = (parsed.SUPABASE_KEY || env("SUPABASE_KEY")).trim();
    const WHOIS_API_KEY = (parsed.WHOIS_API_KEY || env("WHOIS_API_KEY")).trim();
    const PAGESPEED_API_KEY = (parsed.PAGESPEED_API_KEY || env("PAGESPEED_API_KEY")).trim();
    const ELEVEN_LABS_API_KEY = (parsed.ELEVEN_LABS_API_KEY || env("ELEVEN_LABS_API_KEY") || env("ELEVENLABS_API_KEY")).trim();
    const RESEND_API_KEY = (parsed.RESEND_API_KEY || env("RESEND_API_KEY")).trim();
    const TWILIO_ACCOUNT_SID = (parsed.TWILIO_ACCOUNT_SID || env("TWILIO_ACCOUNT_SID")).trim();
    const TWILIO_AUTH_TOKEN = (parsed.TWILIO_AUTH_TOKEN || env("TWILIO_AUTH_TOKEN")).trim();
    const TELEGRAM_BOT_TOKEN = (parsed.TELEGRAM_BOT_TOKEN || env("TELEGRAM_BOT_TOKEN")).trim();
    const APIFY_TOKEN = (parsed.APIFY_TOKEN || env("APIFY_TOKEN")).trim();

    const required = [
      ["DATABASE_URL", DATABASE_URL],
      ["SUPABASE_KEY", SUPABASE_KEY],
      ["WHOIS_API_KEY", WHOIS_API_KEY],
      ["PAGESPEED_API_KEY", PAGESPEED_API_KEY],
      ["ELEVEN_LABS_API_KEY", ELEVEN_LABS_API_KEY],
      ["RESEND_API_KEY", RESEND_API_KEY],
      ["TWILIO_ACCOUNT_SID", TWILIO_ACCOUNT_SID],
      ["TWILIO_AUTH_TOKEN", TWILIO_AUTH_TOKEN],
      ["TELEGRAM_BOT_TOKEN", TELEGRAM_BOT_TOKEN],
      ["APIFY_TOKEN", APIFY_TOKEN],
    ] as const;
    const missing = required.filter(([, v]) => !v).map(([k]) => k);
    if (missing.length) {
      throw new Error(`Missing env vars for validation: ${missing.join(", ")}`);
    }

    // 1) Database URL: basic connectivity check.
    try {
      const db = postgres(DATABASE_URL, { max: 1, prepare: false });
      try {
        await db`select 1 as ok`;
        issues.push({ service: "DATABASE_URL", ok: true, detail: "Connected and ran `select 1`." });
      } finally {
        await db.end({ timeout: 5 });
      }
    } catch (e: any) {
      throw new Error(`DATABASE_URL invalid/unreachable: ${String(e?.message ?? e)}`);
    }

    // 2) Supabase anon key: try calling PostgREST if we can derive project URL.
    try {
      const ref = parseSupabaseProjectRefFromDbUrl(DATABASE_URL);
      if (!ref) throw new Error("Could not derive Supabase project ref from DATABASE_URL host.");
      const supabaseUrl = `https://${ref}.supabase.co`;
      const res = await fetchJson(`${supabaseUrl}/rest/v1/`, {
        headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
      });
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      // PostgREST root may 404/400 but should not 401 when key is accepted.
      issues.push({ service: "SUPABASE_KEY", ok: true, status: res.status, detail: `Called ${supabaseUrl}/rest/v1/ (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`SUPABASE_KEY invalid: ${String(e?.message ?? e)}`);
    }

    // 3) WhoisXML: WHOIS lookup
    try {
      const url =
        `https://www.whoisxmlapi.com/whoisserver/WhoisService?apiKey=${encodeURIComponent(WHOIS_API_KEY)}` +
        `&domainName=${encodeURIComponent(testDomain)}&outputFormat=JSON`;
      const res = await fetchJson(url, { timeoutMs: 20_000 });
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      if (typeof res.text === "string" && /invalid api key/i.test(res.text)) throw new Error("Invalid API key.");
      issues.push({ service: "WHOIS_API_KEY", ok: true, status: res.status, detail: `WHOIS lookup ok (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`WHOIS_API_KEY invalid: ${String(e?.message ?? e)}`);
    }

    // 4) PageSpeed: lightweight runPagespeed
    try {
      const url =
        `https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${encodeURIComponent(`https://${testDomain}`)}` +
        `&key=${encodeURIComponent(PAGESPEED_API_KEY)}`;
      const res = await fetchJson(url, { timeoutMs: 20_000 });
      if (!res.ok && res.status === 400 && typeof res.text === "string" && /API key not valid/i.test(res.text)) {
        throw new Error("API key not valid.");
      }
      if (!res.ok && res.status === 403) throw new Error("Forbidden (403) — key may be restricted or quota exceeded.");
      issues.push({ service: "PAGESPEED_API_KEY", ok: true, status: res.status, detail: `runPagespeed ok (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`PAGESPEED_API_KEY invalid: ${String(e?.message ?? e)}`);
    }

    // 5) ElevenLabs: user endpoint
    try {
      const res = await fetchJson("https://api.elevenlabs.io/v1/user", {
        headers: { "xi-api-key": ELEVEN_LABS_API_KEY },
      });
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      issues.push({ service: "ELEVEN_LABS_API_KEY", ok: true, status: res.status, detail: `Called /v1/user (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`ELEVEN_LABS_API_KEY invalid: ${String(e?.message ?? e)}`);
    }

    // 6) Resend: list domains
    try {
      const res = await fetchJson("https://api.resend.com/domains", {
        headers: { Authorization: `Bearer ${RESEND_API_KEY}` },
      });
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      issues.push({ service: "RESEND_API_KEY", ok: true, status: res.status, detail: `Called /domains (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`RESEND_API_KEY invalid: ${String(e?.message ?? e)}`);
    }

    // 7) Twilio: list accounts (basic auth)
    try {
      const auth = Buffer.from(`${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}`, "utf8").toString("base64");
      const res = await fetchJson("https://api.twilio.com/2010-04-01/Accounts.json?PageSize=1", {
        headers: { Authorization: `Basic ${auth}` },
      });
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      issues.push({ service: "TWILIO_AUTH", ok: true, status: res.status, detail: `Called Accounts.json (status ${res.status}).` });
    } catch (e: any) {
      throw new Error(`Twilio credentials invalid: ${String(e?.message ?? e)}`);
    }

    // 8) Telegram: getMe
    try {
      const res = await fetchJson(`https://api.telegram.org/bot${encodeURIComponent(TELEGRAM_BOT_TOKEN)}/getMe`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const ok = Boolean((res.json as any)?.ok);
      if (!ok) throw new Error(`Response not ok: ${res.text.slice(0, 200)}`);
      issues.push({ service: "TELEGRAM_BOT_TOKEN", ok: true, status: res.status, detail: "Called getMe." });
    } catch (e: any) {
      throw new Error(`TELEGRAM_BOT_TOKEN invalid: ${String(e?.message ?? e)}`);
    }

    // 9) Apify: users/me
    try {
      const res = await fetchJson(`https://api.apify.com/v2/users/me?token=${encodeURIComponent(APIFY_TOKEN)}`);
      if (!res.ok && res.status === 401) throw new Error("Unauthorized (401).");
      issues.push({ service: "APIFY_TOKEN", ok: true, status: res.status, detail: "Called /v2/users/me." });
    } catch (e: any) {
      throw new Error(`APIFY_TOKEN invalid: ${String(e?.message ?? e)}`);
    }

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              ok: true,
              validated: issues.map((i) => ({ ...i, detail: i.detail.replaceAll(SUPABASE_KEY, redact(SUPABASE_KEY)) })),
              note: "Validation succeeded. If providers enforce IP restrictions/quotas, failures may be intermittent.",
            },
            null,
            2,
          ),
        },
      ],
    };
  }

  throw new Error(`Unknown tool: ${name}`);
});

function repoRoot() {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  return join(__dirname, "..", "..");
}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

